// cmd/context.go — emily context build
//
// Compiles all Tier 1 golden docs from all repos into
// EMILY/context/full-system-context.md via claude-haiku bilingual compression.
// Runs synchronously — use as a one-shot refresh before planning sessions.

package cmd

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/emilyspringerton/emily-cli/internal/config"
)

type goldenSource struct {
	Name   string
	Path   string
	Budget int // max chars; 0 = unlimited
}

// RunContext dispatches emily context subcommands.
func RunContext(args []string) int {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "emily context: missing subcommand. Try: build")
		return 1
	}
	switch args[0] {
	case "build":
		return runContextBuild(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "emily context: unknown subcommand %q — try: build\n", args[0])
		return 1
	}
}

func runContextBuild(args []string) int {
	fs := flag.NewFlagSet("context build", flag.ContinueOnError)
	dryRun := fs.Bool("dry-run", false, "print what would be written without writing")
	if err := fs.Parse(args); err != nil {
		return 1
	}

	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		fmt.Fprintln(os.Stderr, "emily context build: ANTHROPIC_API_KEY not set — writing raw (uncompressed) context")
	}

	cfg, err := config.Resolve()
	if err != nil {
		fmt.Fprintf(os.Stderr, "config: %v\n", err)
		return 1
	}

	base := filepath.Dir(cfg.EmilyRoot)
	indexPath := filepath.Join(cfg.EmilyRoot, "context", "golden-docs-index.md")
	sources := loadContextIndex(indexPath, base)

	outPath := filepath.Join(cfg.EmilyRoot, "context", "full-system-context.md")
	fmt.Printf("emily context build: compiling %d golden sources → %s\n", len(sources), outPath)

	var sections []string
	built := 0
	for _, src := range sources {
		raw, err := os.ReadFile(src.Path)
		if err != nil {
			fmt.Printf("  skip %-18s  (not found)\n", src.Name)
			continue
		}
		text := string(raw)
		if src.Budget > 0 && len(text) > src.Budget {
			text = text[:src.Budget]
		}
		var compressed string
		if apiKey == "" {
			compressed = fmt.Sprintf("## %s\n%s\n", src.Name, text)
			fmt.Printf("  %-18s  raw (%d chars)\n", src.Name, len(text))
		} else {
			var err error
			compressed, err = contextCompress(apiKey, src.Name, text)
			if err != nil {
				fmt.Printf("  %-18s  compress failed: %v\n", src.Name, err)
				if len(text) > 500 {
					text = text[:500]
				}
				compressed = fmt.Sprintf("## %s\n%s\n", src.Name, text)
			} else {
				fmt.Printf("  ✓ %-16s  ~%d tokens\n", src.Name, len(compressed)/4)
			}
		}
		sections = append(sections, compressed)
		built++
	}

	mode := "haiku-compressed bilingual"
	if apiKey == "" {
		mode = "raw (no ANTHROPIC_API_KEY — run emily context build with key for compression)"
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("# 全系統上下文 FULL SYSTEM CONTEXT — %s\n", time.Now().UTC().Format("2006-01-02")))
	b.WriteString(fmt.Sprintf("*Auto-generated by `emily context build`. Mode: %s.*\n", mode))
	b.WriteString(fmt.Sprintf("*Sources compiled: %d/%d.*\n\n", built, len(sources)))
	for _, s := range sections {
		b.WriteString(s)
		b.WriteString("\n")
	}
	output := b.String()

	if *dryRun {
		fmt.Printf("\n--- preview (%d chars) ---\n%s\n", len(output), output[:min(len(output), 800)])
		return 0
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		return 3
	}
	if err := os.WriteFile(outPath, []byte(output), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		return 3
	}
	fmt.Printf("\n✓ %s written (%d bytes, %d sources)\n", outPath, len(output), built)
	return 0
}

func contextCompress(apiKey, name, text string) (string, error) {
	system := `You are Emily Prime's context compressor for EINHORN_INDUSTRIAL.
Compress documentation into a dense ≤180 token bilingual section.
Rules:
- Chinese for concepts/state (系統/北極星/完成/待辦/架構), English for technical names/APIs/file paths
- Every token carries signal — no filler, no repetition
- Preserve: purpose, current status, open blockers, key interfaces/endpoints/paths
- Start with ## NAME (use the exact label provided)
- Output ONLY the compressed section`

	body := map[string]any{
		"model":      "claude-haiku-4-5-20251001",
		"max_tokens": 400,
		"system":     system,
		"messages": []map[string]any{
			{"role": "user", "content": fmt.Sprintf("Label: %s\n\nDoc:\n%s", name, text)},
		},
	}
	payload, _ := json.Marshal(body)

	req, err := http.NewRequest("POST", "https://api.anthropic.com/v1/messages", bytes.NewReader(payload))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("api %d: %s", resp.StatusCode, raw)
	}

	var result struct {
		Content []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		} `json:"content"`
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return "", fmt.Errorf("parse: %w", err)
	}
	for _, block := range result.Content {
		if block.Type == "text" {
			return strings.TrimSpace(block.Text) + "\n", nil
		}
	}
	return "", fmt.Errorf("no text block")
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// loadContextIndex parses EMILY/context/golden-docs-index.md and returns goldenSources
// for all Tier 1 rows. Falls back to the hardcoded list if the file can't be read.
func loadContextIndex(indexPath, base string) []goldenSource {
	data, err := os.ReadFile(indexPath)
	if err != nil {
		return hardcodedContextSources(base)
	}
	var sources []goldenSource
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "|---") || strings.HasPrefix(line, "| name") {
			continue
		}
		fields := strings.Split(line, "|")
		if len(fields) < 6 {
			continue
		}
		name := strings.TrimSpace(fields[1])
		relPath := strings.TrimSpace(fields[2])
		tier := strings.TrimSpace(fields[3])
		budgetStr := strings.TrimSpace(fields[4])
		if name == "" || relPath == "" || tier != "1" {
			continue
		}
		budget, _ := strconv.Atoi(budgetStr)
		sources = append(sources, goldenSource{
			Name:   name,
			Path:   filepath.Join(base, relPath),
			Budget: budget,
		})
	}
	if len(sources) == 0 {
		return hardcodedContextSources(base)
	}
	return sources
}

func hardcodedContextSources(base string) []goldenSource {
	return []goldenSource{
		{Name: "FATBABY", Path: filepath.Join(base, "PRRJECT_FATBABY/docs/northstar/northstar.md"), Budget: 8000},
		{Name: "FATBABY-EXEC", Path: filepath.Join(base, "PRRJECT_FATBABY/docs/northstar/executive_summary.md"), Budget: 4000},
		{Name: "EMILY-SPEC", Path: filepath.Join(base, "EMILY/emily-prime-spec.md"), Budget: 4000},
		{Name: "EMILY-NORTH", Path: filepath.Join(base, "EMILY/docs/NORTHSTAR.md"), Budget: 3000},
		{Name: "EMILY-BACKLOG", Path: filepath.Join(base, "EMILY/GOLDEN.md"), Budget: 0},
		{Name: "EMIREE", Path: filepath.Join(base, "EMILY/emiree-emily-fatbaby.md"), Budget: 4000},
		{Name: "RSI-ENGINE", Path: filepath.Join(base, "EMILY/docs/emily-rsi-engine-spec.md"), Budget: 0},
		{Name: "EMIREE-SPEC", Path: filepath.Join(base, "EMILY/docs/emiree-over-agent-spec.md"), Budget: 0},
		{Name: "IDUNA", Path: filepath.Join(base, "IDUNA/golden.md"), Budget: 3000},
		{Name: "APPLES", Path: filepath.Join(base, "APPLES/docs/NORTHSTAR.md"), Budget: 0},
		{Name: "MJOLNIR", Path: filepath.Join(base, "MJOLNIR/docs/NORTHSTAR.md"), Budget: 0},
		{Name: "SHANKPIT", Path: filepath.Join(base, "SHANKPIT/docs2/NORTHSTAR.md"), Budget: 4000},
		{Name: "EMILYOS", Path: filepath.Join(base, "EmilyOS/docs/NORTHSTAR.md"), Budget: 0},
		{Name: "PITVIPER", Path: filepath.Join(base, "PITVIPER/docs/NORTHSTAR.md"), Budget: 0},
		{Name: "EMILY-CLI", Path: filepath.Join(base, "emily.cli/docs/NORTHSTAR.md"), Budget: 0},
		{Name: "GTM", Path: filepath.Join(base, "PRRJECT_FATBABY/docs/GTM_FUNNEL.md"), Budget: 3000},
		{Name: "TRAINING", Path: filepath.Join(base, "EMILY/docs/TRAINING_PIPELINE.md"), Budget: 2000},
		{Name: "EDIS", Path: filepath.Join(base, "EDIS/NORTHSTAR.md"), Budget: 3000},
	}
}
