// cmd/context.go — emily context build
//
// Compiles all Tier 1 golden docs from all repos into
// EMILY/context/full-system-context.md via a pure-CLI extractive summary —
// no LLM call, no ANTHROPIC_API_KEY. Runs synchronously — use as a one-shot
// refresh before planning sessions.
//
// Founder real-time, 2026-08-25: "the golden doc index should not be LLM
// powered we can do that pure cli" — this had previously haiku-compressed
// each source (see git history), which meant the whole index sat blocked on
// ANTHROPIC_API_KEY having credit (HITL-11, dead since 2026-07-19, still
// dead as of this rewrite). Deterministic string processing has no such
// dependency and never can fail on a billing issue.

package cmd

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/emilyspringerton/emily-cli/internal/config"
)

type goldenSource struct {
	Name   string
	Path   string
	Budget int // max chars; 0 = unlimited
}

// RunContext dispatches emily context subcommands.
func RunContext(args []string) int {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "emily context: missing subcommand. Try: build")
		return 1
	}
	switch args[0] {
	case "build":
		return runContextBuild(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "emily context: unknown subcommand %q — try: build\n", args[0])
		return 1
	}
}

func runContextBuild(args []string) int {
	fs := flag.NewFlagSet("context build", flag.ContinueOnError)
	dryRun := fs.Bool("dry-run", false, "print what would be written without writing")
	if err := fs.Parse(args); err != nil {
		return 1
	}

	cfg, err := config.Resolve()
	if err != nil {
		fmt.Fprintf(os.Stderr, "config: %v\n", err)
		return 1
	}

	base := filepath.Dir(cfg.EmilyRoot)
	indexPath := filepath.Join(cfg.EmilyRoot, "context", "golden-docs-index.md")
	sources := loadContextIndex(indexPath, base)

	outPath := filepath.Join(cfg.EmilyRoot, "context", "full-system-context.md")
	fmt.Printf("emily context build: compiling %d golden sources → %s\n", len(sources), outPath)

	var sections []string
	built := 0
	for _, src := range sources {
		raw, err := os.ReadFile(src.Path)
		if err != nil {
			fmt.Printf("  skip %-18s  (not found)\n", src.Name)
			continue
		}
		text := string(raw)
		if src.Budget > 0 && len(text) > src.Budget {
			text = text[:src.Budget]
		}
		compressed := pureCompress(src.Name, text, 900)
		fmt.Printf("  %-18s  %d → %d chars\n", src.Name, len(text), len(compressed))
		sections = append(sections, compressed)
		built++
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# 全系統上下文 FULL SYSTEM CONTEXT — %s\n", time.Now().UTC().Format("2006-01-02")))
	b.WriteString("*Auto-generated by `emily context build`. Mode: pure-CLI extractive summary (no LLM, no ANTHROPIC_API_KEY).*\n")
	b.WriteString(fmt.Sprintf("*Sources compiled: %d/%d.*\n\n", built, len(sources)))
	for _, s := range sections {
		b.WriteString(s)
		b.WriteString("\n")
	}
	output := b.String()

	if *dryRun {
		fmt.Printf("\n--- preview (%d chars) ---\n%s\n", len(output), output[:min(len(output), 800)])
		return 0
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		return 3
	}
	if err := os.WriteFile(outPath, []byte(output), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		return 3
	}
	fmt.Printf("\n✓ %s written (%d bytes, %d sources)\n", outPath, len(output), built)
	return 0
}

// pureCompress produces a dense, deterministic (non-LLM) extractive summary
// of a golden doc: every markdown header line, plus its first non-blank body
// line (the real signal-carrying "lead line" an extractive summarizer keeps),
// capped to maxChars. No network call, no API key, ever — same shape/intent
// as the old haiku-compressed section (a "## NAME" header followed by dense
// structure), just built with string processing instead of an LLM call.
func pureCompress(name, text string, maxChars int) string {
	if maxChars <= 0 {
		maxChars = 900 // ~180-220 tokens at ~4-5 chars/token, matching the old haiku target
	}
	var b strings.Builder
	b.WriteString("## " + name + "\n")

	lines := strings.Split(text, "\n")
	sawHeader := false
	pendingHeader := false
	for _, raw := range lines {
		trimmed := strings.TrimSpace(raw)
		if trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, "#") {
			sawHeader = true
			pendingHeader = true
			// Downshift one level so it nests under this section's own "## NAME".
			b.WriteString("#" + trimmed + "\n")
			if b.Len() >= maxChars {
				break
			}
			continue
		}
		if pendingHeader {
			b.WriteString("- " + trimmed + "\n")
			pendingHeader = false
			if b.Len() >= maxChars {
				break
			}
		}
	}

	if !sawHeader {
		// No markdown structure to extract from (a plain-text/data doc) —
		// fall back to the first maxChars of real content, collapsing blank lines.
		b.Reset()
		b.WriteString("## " + name + "\n")
		for _, raw := range lines {
			trimmed := strings.TrimSpace(raw)
			if trimmed == "" {
				continue
			}
			b.WriteString(trimmed + "\n")
			if b.Len() >= maxChars {
				break
			}
		}
	}

	out := b.String()
	if len(out) > maxChars {
		out = out[:maxChars] + "…\n"
	}
	return out
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// loadContextIndex parses EMILY/context/golden-docs-index.md and returns goldenSources
// for all Tier 1 rows. Falls back to the hardcoded list if the file can't be read.
func loadContextIndex(indexPath, base string) []goldenSource {
	data, err := os.ReadFile(indexPath)
	if err != nil {
		return hardcodedContextSources(base)
	}
	var sources []goldenSource
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "|---") || strings.HasPrefix(line, "| name") {
			continue
		}
		fields := strings.Split(line, "|")
		if len(fields) < 6 {
			continue
		}
		name := strings.TrimSpace(fields[1])
		relPath := strings.TrimSpace(fields[2])
		tier := strings.TrimSpace(fields[3])
		budgetStr := strings.TrimSpace(fields[4])
		if name == "" || relPath == "" || tier != "1" {
			continue
		}
		budget, _ := strconv.Atoi(budgetStr)
		sources = append(sources, goldenSource{
			Name:   name,
			Path:   filepath.Join(base, relPath),
			Budget: budget,
		})
	}
	if len(sources) == 0 {
		return hardcodedContextSources(base)
	}
	return sources
}

func hardcodedContextSources(base string) []goldenSource {
	return []goldenSource{
		{Name: "FATBABY", Path: filepath.Join(base, "PRRJECT_FATBABY/docs/northstar/northstar.md"), Budget: 8000},
		{Name: "FATBABY-EXEC", Path: filepath.Join(base, "PRRJECT_FATBABY/docs/northstar/executive_summary.md"), Budget: 4000},
		{Name: "EMILY-SPEC", Path: filepath.Join(base, "EMILY/emily-prime-spec.md"), Budget: 4000},
		{Name: "EMILY-NORTH", Path: filepath.Join(base, "EMILY/docs/NORTHSTAR.md"), Budget: 3000},
		{Name: "EMILY-BACKLOG", Path: filepath.Join(base, "EMILY/GOLDEN.md"), Budget: 0},
		{Name: "EMIREE", Path: filepath.Join(base, "EMILY/emiree-emily-fatbaby.md"), Budget: 4000},
		{Name: "RSI-ENGINE", Path: filepath.Join(base, "EMILY/docs/emily-rsi-engine-spec.md"), Budget: 0},
		{Name: "EMIREE-SPEC", Path: filepath.Join(base, "EMILY/docs/emiree-over-agent-spec.md"), Budget: 0},
		{Name: "IDUNA", Path: filepath.Join(base, "IDUNA/golden.md"), Budget: 3000},
		{Name: "APPLES", Path: filepath.Join(base, "APPLES/docs/NORTHSTAR.md"), Budget: 0},
		{Name: "MJOLNIR", Path: filepath.Join(base, "MJOLNIR/docs/NORTHSTAR.md"), Budget: 0},
		{Name: "SHANKPIT", Path: filepath.Join(base, "SHANKPIT/docs2/NORTHSTAR.md"), Budget: 4000},
		{Name: "EMILYOS", Path: filepath.Join(base, "EmilyOS/docs/NORTHSTAR.md"), Budget: 0},
		{Name: "PITVIPER", Path: filepath.Join(base, "PITVIPER/docs/NORTHSTAR.md"), Budget: 0},
		{Name: "EMILY-CLI", Path: filepath.Join(base, "emily.cli/docs/NORTHSTAR.md"), Budget: 0},
		{Name: "GTM", Path: filepath.Join(base, "PRRJECT_FATBABY/docs/GTM_FUNNEL.md"), Budget: 3000},
		{Name: "TRAINING", Path: filepath.Join(base, "EMILY/docs/TRAINING_PIPELINE.md"), Budget: 2000},
		{Name: "EDIS", Path: filepath.Join(base, "EDIS/NORTHSTAR.md"), Budget: 3000},
	}
}
